/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudey.Nomad.Client.Model;
using Cloudey.Nomad.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudey.Nomad.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ACLTokenRoleLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ACLTokenRoleLinkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ACLTokenRoleLink
        //private ACLTokenRoleLink instance;

        public ACLTokenRoleLinkTests()
        {
            // TODO uncomment below to create an instance of ACLTokenRoleLink
            //instance = new ACLTokenRoleLink();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ACLTokenRoleLink
        /// </summary>
        [Fact]
        public void ACLTokenRoleLinkInstanceTest()
        {
            // TODO uncomment below to test "IsType" ACLTokenRoleLink
            //Assert.IsType<ACLTokenRoleLink>(instance);
        }


        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
