/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudey.Nomad.Client.Model;
using Cloudey.Nomad.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudey.Nomad.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ChangeScript
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChangeScriptTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChangeScript
        //private ChangeScript instance;

        public ChangeScriptTests()
        {
            // TODO uncomment below to create an instance of ChangeScript
            //instance = new ChangeScript();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChangeScript
        /// </summary>
        [Fact]
        public void ChangeScriptInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChangeScript
            //Assert.IsType<ChangeScript>(instance);
        }


        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Fact]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }
        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }
        /// <summary>
        /// Test the property 'FailOnError'
        /// </summary>
        [Fact]
        public void FailOnErrorTest()
        {
            // TODO unit test for the property 'FailOnError'
        }
        /// <summary>
        /// Test the property 'Timeout'
        /// </summary>
        [Fact]
        public void TimeoutTest()
        {
            // TODO unit test for the property 'Timeout'
        }

    }

}
