/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudey.Nomad.Client.Model;
using Cloudey.Nomad.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudey.Nomad.Client.Test.Model
{
    /// <summary>
    ///  Class for testing JobACL
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JobACLTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JobACL
        //private JobACL instance;

        public JobACLTests()
        {
            // TODO uncomment below to create an instance of JobACL
            //instance = new JobACL();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JobACL
        /// </summary>
        [Fact]
        public void JobACLInstanceTest()
        {
            // TODO uncomment below to test "IsType" JobACL
            //Assert.IsType<JobACL>(instance);
        }


        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
        /// <summary>
        /// Test the property 'JobID'
        /// </summary>
        [Fact]
        public void JobIDTest()
        {
            // TODO unit test for the property 'JobID'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'Task'
        /// </summary>
        [Fact]
        public void TaskTest()
        {
            // TODO unit test for the property 'Task'
        }

    }

}
