/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Cloudey.Nomad.Client.Model;
using Cloudey.Nomad.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Cloudey.Nomad.Client.Test.Model
{
    /// <summary>
    ///  Class for testing VariableMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VariableMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VariableMetadata
        //private VariableMetadata instance;

        public VariableMetadataTests()
        {
            // TODO uncomment below to create an instance of VariableMetadata
            //instance = new VariableMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VariableMetadata
        /// </summary>
        [Fact]
        public void VariableMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" VariableMetadata
            //Assert.IsType<VariableMetadata>(instance);
        }


        /// <summary>
        /// Test the property 'CreateIndex'
        /// </summary>
        [Fact]
        public void CreateIndexTest()
        {
            // TODO unit test for the property 'CreateIndex'
        }
        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }
        /// <summary>
        /// Test the property 'ModifyIndex'
        /// </summary>
        [Fact]
        public void ModifyIndexTest()
        {
            // TODO unit test for the property 'ModifyIndex'
        }
        /// <summary>
        /// Test the property 'ModifyTime'
        /// </summary>
        [Fact]
        public void ModifyTimeTest()
        {
            // TODO unit test for the property 'ModifyTime'
        }
        /// <summary>
        /// Test the property 'Namespace'
        /// </summary>
        [Fact]
        public void NamespaceTest()
        {
            // TODO unit test for the property 'Namespace'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

    }

}
